### ISSUE TITLE
Conda-Store server api/ui status for jobs is inconsistent at times

### ISSUE THREAD

**Issue by costrouc** [conda-incubator/conda-store#459] opened 2023-04-13 12:52 UTC
This line is supposed to clear up the sqlalchemy session state after every request https://github.com/Quansight/conda-store/blob/main/conda-store-server/conda_store_server/server/app.py#L224. I do not think this is fully happening. 

I would use flask_sqlalcheny for inspiration on how this should properly be done https://flask-sqlalchemy.palletsprojects.com/en/3.0.x/. https://github.com/pallets-eco/flask-sqlalchemy.

**Comment by trallard** [comment] 2024-10-16 16:09
@peytondmurray I am not sure if this is still the current behaviour, when you get a chance can you have a look?

**Comment by peytondmurray** [comment] 2024-10-18 23:53
The first link is broken at this point, and I'm not sure what was being pointed to. I'm closing now unless we have a more concrete understanding of what the issue is here.

**Closed by peytondmurray** 2024-10-18 23:53 UTC
Labels: type: bug 🐛, needs: discussion 💬
