### ISSUE TITLE
conda-store-worker not downloading repodata for `main` channel

### ISSUE THREAD

**Issue by iameskild** [conda-incubator/conda-store#602] opened 2023-09-29 02:31 UTC
It's a little tricker determining what effects this has been it's means worth raising as a potential issue.

```
conda-store-worker [2023-09-28 23:17:03,143: INFO/MainProcess] mingle: searching for neighbors
conda-store-worker [2023-09-28 23:17:04,158: INFO/MainProcess] mingle: all alone
conda-store-worker [2023-09-28 23:17:04,191: INFO/MainProcess] celery@nebari-conda-store-worker-b798c94ff-vfwww ready.
conda-store-worker [2023-09-28 23:17:04,198: INFO/MainProcess] Task task_update_conda_channels[206ca64e-a503-4149-826e-8368063ab543] received
conda-store-worker [2023-09-28 23:17:04,205: INFO/MainProcess] Task task_watch_paths[51ca63d7-af72-4f83-8b83-129c26c0c158] received
conda-store-worker [2023-09-28 23:17:04,209: INFO/MainProcess] Task task_cleanup_builds[9368ac21-7213-48de-af75-64e44f2143ac] received
conda-store-worker [2023-09-28 23:17:04,285: WARNING/ForkPoolWorker-2] [CondaStoreWorker] updating conda store channels
conda-store-worker [2023-09-28 23:17:04,361: INFO/MainProcess] Task task_update_conda_channel[5248d799-96c3-4bd6-826f-f4af193da9ae] received
conda-store-worker [2023-09-28 23:17:04,364: INFO/MainProcess] Task task_update_conda_channel[575c35ac-9ea0-44b2-9d04-4dee01c42f24] received
conda-store-worker [2023-09-28 23:17:04,365: INFO/ForkPoolWorker-2] Task task_update_conda_channels[206ca64e-a503-4149-826e-8368063ab543] succeeded in 0.16587088600499555s: None
conda-store-worker [2023-09-28 23:17:04,367: INFO/MainProcess] Task task_update_conda_channel[24a2d19c-0d27-4b3a-bb16-72add1e710cf] received
conda-store-worker [2023-09-28 23:17:04,397: INFO/ForkPoolWorker-2] update packages https://conda.anaconda.org/conda-forge 
conda-store-worker [2023-09-28 23:17:04,398: INFO/ForkPoolWorker-2] Downloading repodata ...  
conda-store-worker [2023-09-28 23:17:04,410: INFO/ForkPoolWorker-5] Task task_watch_paths[51ca63d7-af72-4f83-8b83-129c26c0c158] succeeded in 0.20355661900248379s: None
conda-store-worker [2023-09-28 23:17:04,439: INFO/ForkPoolWorker-5] update packages https://repo.anaconda.com/pkgs/main 
conda-store-worker [2023-09-28 23:17:04,439: INFO/ForkPoolWorker-5] Downloading repodata ...  
conda-store-worker [2023-09-28 23:17:04,476: INFO/ForkPoolWorker-4] update packages https://conda.anaconda.org/main 
conda-store-worker [2023-09-28 23:17:04,476: INFO/ForkPoolWorker-4] Downloading repodata ...  
conda-store-worker [2023-09-28 23:17:04,743: ERROR/ForkPoolWorker-4] Task task_update_conda_channel[5248d799-96c3-4bd6-826f-f4af193da9ae] raised unexpected: HTTPError('404 Client Error: Not Found for url: https://conda.anaconda.org/main/channeldata.json')
conda-store-worker Traceback (most recent call last):
conda-store-worker   File "/opt/conda/envs/conda-store-server/lib/python3.10/site-packages/celery/app/trace.py", line 477, in trace_task
conda-store-worker     R = retval = fun(*args, **kwargs)
conda-store-worker   File "/opt/conda/envs/conda-store-server/lib/python3.10/site-packages/celery/app/trace.py", line 760, in __protected_call__
conda-store-worker     return self.run(*args, **kwargs)
conda-store-worker   File "/opt/conda/envs/conda-store-server/lib/python3.10/site-packages/conda_store_server/worker/tasks.py", line 152, in task_update_conda_channel
conda-store-worker     channel.update_packages(db, subdirs=settings.conda_platforms)
conda-store-worker   File "/opt/conda/envs/conda-store-server/lib/python3.10/site-packages/conda_store_server/orm.py", line 348, in update_packages
conda-store-worker     repodata = conda_utils.download_repodata(
conda-store-worker   File "/opt/conda/envs/conda-store-server/lib/python3.10/site-packages/conda_store_server/conda_utils.py", line 152, in download_repodata
conda-store-worker     response.raise_for_status()
conda-store-worker   File "/opt/conda/envs/conda-store-server/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
conda-store-worker     raise HTTPError(http_error_msg, response=self)
conda-store-worker requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://conda.anaconda.org/main/channeldata.json

```

I found [this note](https://github.com/conda-incubator/conda-store/blob/64552a28e649d7305ec971332cfb739286769ec9/conda-store-server/conda_store_server/conda_utils.py#L127-L130) about the channeldata.json for the main channel which makes me think this was working at one point.

**Comment by asmeurer** [comment] 2023-09-29 07:10
I also see this error all the time, but I think it can be safely ignored. Maybe channeldata is only a conda-forge thing? It does exist for that channel https://conda.anaconda.org/conda-forge/channeldata.json

**Comment by nkaretnikov** [comment] 2023-12-13 13:45
@trallard just want to confirm: is this in the Ready state because of what Aaron wrote above? Can this be closed?

**Comment by nkaretnikov** [comment] 2023-12-16 19:19
I cannot reproduce this as of 5e4e2e5. Perhaps Eskild was using an old version that didn't have a fix linked in the original message. Or something has changed since then and made the replacement work again.

I've added some prints to `download_repodata` to make sure the replacement there is working:

```py
    # the conda main channel does not have a channeldata.json within
    # the https://conda.anaconda.org/<channel>/channeldata.json
    # so we replace the given url with it's equivalent alias
    channel_replacements = {
        "https://conda.anaconda.org/main/": yarl.URL(
            "https://repo.anaconda.com/pkgs/main"
        )
    }
    normalized_channel_url = yarl.URL(channel) / "./"
    channel_url = channel_replacements.get(
        str(normalized_channel_url), yarl.URL(channel)
    )
    print(f"XXX: >{channel}<, >{normalized_channel_url}<, >{channel_url}<")

...

    response = requests.get(channel_url / "channeldata.json", headers=headers)
    if response.status_code == 304:  # 304 Not Modified since last_update
        return {"architectures": {}}
    response.raise_for_status()
    print("XXX: response", response.status_code)
```

Indeed, it does:

```
[2023-12-16 20:03:20,185: INFO/ForkPoolWorker-2] update packages https://conda.anaconda.org/main
[2023-12-16 20:03:20,185: INFO/ForkPoolWorker-2] Downloading repodata ...
[2023-12-16 20:03:20,186: WARNING/ForkPoolWorker-2] XXX: >https://conda.anaconda.org/main<, >https://conda.anaconda.org/main/<, >https://repo.anaconda.com/pkgs/main<
[2023-12-16 20:03:20,418: WARNING/ForkPoolWorker-2] XXX: response
[2023-12-16 20:03:20,419: WARNING/ForkPoolWorker-2] 200
```

You can go to this link to confirm:
https://repo.anaconda.com/pkgs/main/channeldata.json

So I'm going to close this.

**Comment by nkaretnikov** [comment] 2023-12-17 19:52
I've reproduced this on Windows.

On Linux:

```
In [2]: yarl.URL("foo") / "./"
Out[2]: URL('foo/')
```

On Windows the slash is not appended, so the lookup in `channel_replacements` fails:

```
In [4]: yarl.URL("foo") / "./"
Out[4]: URL('foo')
```

**Closed** 2023-12-20 18:49 UTC
Labels: type: bug 🐛, area: dependencies 📦, area: user experience 👩🏻‍💻
