### ISSUE TITLE
[BUG] - Cannot log out via http://localhost:8080/conda-store/

### ISSUE THREAD

**Issue by nkaretnikov** [conda-incubator/conda-store#684] opened 2023-12-04 05:02 UTC
### Describe the bug

- Go to this URL (note: it's the server port)
- Click on "Log out"
- Get redirected to the same page, not logged out. 

### Expected behavior

Being able to log out.

Logging out via the UI URL works fine: http://localhost:8000/.

This is important for the jupyterlab-conda-store extension.
It uses only the server URL/ports.
So you're able to log in but not log out.
I've just tested this on Nebari using Keycloak auth as well as with standalone conda-store and jupyterlab-conda-store.

### How to Reproduce the problem?

See above.

### Versions and dependencies used.

 4ed688ab68595ed3bbe35b927e00a8011bcb4d43 - server
 4f245dc on top of 1d56d42 - jlab extension

**Comment by kcpevey** [comment] 2023-12-05 18:58
I tested on Nebari v2023.11.0, on the react app not the jlab extension. Not sure what the conda-store version is, but I believe its the latest release.  

I can confirm that clicking the Log out button produces some network traffic, the page looks like it reloads, but I am still logged in (Can still see all the environments and the button is still in "Log out" state. No errors in the js console.

**Comment by kcpevey** [comment] 2024-04-03 15:14
I can confirm that this is an issue in the react app and the extension in the `2024.3.1` release.

**Comment by gabalafou** [comment] 2024-09-11 15:50
Oddly, I cannot reproduce this. Steps I followed:

1. Pulled latest from conda-store-ui: https://github.com/conda-incubator/conda-store-ui/commit/e93a6c1816e5b020afff9e76c4b5c0ab9dda441a
2. `yarn install`
3. `yarn start`
4. Go to http://localhost:8080/conda-store/
  - This is the server-vendored version of the UI, which shows "Version: 2024.3.1" in the lower left
  - If I go to http://localhost:8000/  (port **8000** not 8080), I see "Version: 2024.6.1"
  - The log in / log out button is in the log in state
6. Click "Log in" button in top left, get taken to login form at URL http://localhost:8080/conda-store/login/?next=http://localhost:8080/conda-store/
7. Log in with default username and password
8. Get taken back to http://localhost:8080/conda-store/, the green button in the upper right says "Log out"
9. Click the Log out button
10. Get taken back to http://localhost:8080/conda-store/ and I am logged out

I can repeat these same steps for port 8000 (version 2024.6.1) and I get the same results.

**Comment by peytondmurray** [comment] 2024-09-11 17:14
I tried to reproduce this as well on `conda-store` 3f514525407818fe9021b79441cdcb8a99569741:

1. `docker compose up --build`; waited for everything to start
2. Logged in via localhost:8080/conda-store
3. Created new environment in my username namespace; waited for it to finish.

![image (1)](https://github.com/user-attachments/assets/c850e515-2ee1-4fe9-b98f-d6953dca26b3)

4. Logged out. Cannot see the new environment I just made

![image (2)](https://github.com/user-attachments/assets/b56603d3-ccfa-4119-93e8-cd7bfa89b09a)

**Comment by kcpevey** [comment] 2024-09-11 17:34
This means that either changes to main have resolved this issue, or this is an issue with how Nebari is handling the logout/authentication. Given that nebari auth is routed through keycloak, this seems the more likely reason. We can close this and I'll open up an issue on Nebari to investigate.

**Closed** 2024-09-11 18:19 UTC
Labels: type: bug 🐛, impact: high 🟥
