### ISSUE TITLE
[BUG] - All links on https://conda.store/conda-store/introduction/ are broken

### ISSUE THREAD

**Issue by krassowski** [conda-incubator/conda-store#892] opened 2024-10-14 10:08 UTC
### Describe the bug

All links (except for a link to GitHub repo) on https://conda.store/conda-store/introduction/ show:

![Image](https://github.com/user-attachments/assets/974ff490-fd79-444d-96d3-d84cdf2b0d43)

### Expected behavior

No broken links

### How to Reproduce the problem?

Click on links

### Output

Page Not Found
We could not find what you were looking for.

Please contact the owner of the site that linked you to the original URL and let them know their link is broken.

### Versions and dependencies used.

Current

**Comment by nakul-py** [comment] 2024-10-16 07:28
\assign

**Comment by soapy1** [comment] 2024-10-18 16:10
Looks like this issue was maybe with netlify. I was not able to reproduce this problem using firefox or chrome on multiple devices. Digging into it some with @krassowski and @peytondmurray, it looks like there was some discrepancy in response headers. 

Successful requests would have the header
```
< cache-status: "Netlify Edge"; hit
cache-status: "Netlify Edge"; hit
```

included in the response. Requests that returned a page with broken links would return

```
17:03:25.181616 [0-0] < cache-status: "Netlify Edge"; fwd=miss
cache-status: "Netlify Edge"; fwd=miss
17:03:25.181696 [0-0] * [HTTP/2] [1] header: cache-status: "Netlify Edge"; fwd=miss
```

As of this morning, this seems to have resolved without any changes on our side.

**Closed by soapy1** 2024-10-18 16:10 UTC
Labels: type: bug 🐛
